# Path to credentials
ENV_PATH: "/opt/airflow/dags/project-HLCT/.env"

# Path to requirements
REQUIREMENTS_PATH: "/opt/airflow/dags/project-HLCT/requirements.txt"

# Path to cached venv
VENV_CACHE_PATH: "/opt/airflow/venv-cache/project-HLCT"

# Path to Chrome and Chromedriver binaries
DRIVER_PATH: "/opt/airflow/dags/project-HLCT/deps"

# Base URL to scrape
TARGET_URL: "https://hololive.hololivepro.com/en/talents"
